version: "3.8"

services:
#  testbed-dummy:
#    build:
#     context: ..
#      dockerfile: Dockerfile
#    working_dir: /inventor/testbed
#    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/dummy.yaml | & ./Out-FileByDay.ps1 -BaseName dummy -OutPath ./results/"
#    volumes:
#      - ./results:/inventor/testbed/results

  testbed-webapp.http.dynamic:
    restart: on-failure
    build: 
      context: ..
      dockerfile: Dockerfile.node
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/webapp.http.dynamic.yaml | & ./Out-FileByDay.ps1 -BaseName webapp.http.dynamic -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results
      
  testbed-http:
    build: 
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/webapp.http.yaml | & ./Out-FileByDay.ps1 -BaseName webapp.http -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.smtp:
    build:
      context: ..
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.smtp.yaml | & ./Out-FileByDay.ps1 -BaseName network.smtp -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results

  testbed-security.ssh:
    build:
      context: ..
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/security.ssh.yaml | & ./Out-FileByDay.ps1 -BaseName security.ssh -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.imap:
    build:
      context: ..
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.imap.yaml | & ./Out-FileByDay.ps1 -BaseName network.imap -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.dns:
    build:
      context:
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.dns.yaml | & ./Out-FileByDay.ps1 -BaseName network.dns -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.ntp:
    build:
      context:
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.ntp.yaml | & ./Out-FileByDay.ps1 -BaseName network.ntp -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results

  testbed-security.ldap:
    build:
      context:
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/security.ldap.yaml | & ./Out-FileByDay.ps1 -BaseName security.ldap -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.traceroute:
    build:
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.traceroute.yaml | & ./Out-FileByDay.ps1 -BaseName network.traceroute -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results
  
  testbed-security.tls:
    build:
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -Command "& ./Run-MonitorSession.ps1 -TestSuiteFile schedules/security.tls.yaml | & ./Out-FileByDay.ps1 -BaseName security.tls -OutPath ./results/"
    volumes:
      - ./results:/inventor/testbed/results