version: "3.8"

services:
  testbed-dummy:
    build: 
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/dummy.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.ping:
    build: 
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.ping.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results
      
  testbed-http:
    build: 
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/webapp.http.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.smtp:
    build:
      context: ..
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.smtp.yaml -OutPath ./results/
    wolumes:
      - ./results:/inventor/testbed/results

  testbed-security.ssh:
    build:
      context: ..
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/security.ssh.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.imap:
    build:
      context: ..
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.imap.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results


  testbed-network.dns:
    build:
      context:
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.dns.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results
