version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-server
    depends_on:
      - mongodb

  testbed-dummy:
    build: 
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/dummy.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results

  testbed-network.ping:
    build: 
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/network.ping.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results
      
  testbed-http:
    build: 
      context: ..
      dockerfile: Dockerfile
    working_dir: /inventor/testbed
    command: pwsh -File ./Run-MonitorSession.ps1 -TestSuiteFile schedules/webapp.http.yaml -OutPath ./results/
    volumes:
      - ./results:/inventor/testbed/results
